[book]
authors = ["Anand Chitipothu"]
language = "en"
multilingual = false
src = "docs"
title = "Wireless Networking Setup for Farmhill Learning"

[output.html]
git-repository-url = "https://github.com/farmhill-learning/farmhill-wireless-networking"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/farmhill-learning/farmhill-wireless-networking/edit/main/{path}"
site-url = "/farmhill-wireless-networking/"